# Generated by Django 3.0.7 on 2020-11-23 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('styleKey', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Задача')),
                ('description', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateField(default=datetime.date(2020, 11, 23), verbose_name='Крайний срок выполнения')),
                ('status', models.ManyToManyField(related_name='Статус', to='todo.Status')),
            ],
        ),
    ]
