# Generated by Django 3.0.7 on 2020-12-01 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201124_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.date(2020, 12, 1), verbose_name='Крайний срок выполнения'),
        ),
    ]
