# Generated by Django 3.0.7 on 2020-12-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201204_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='borrower',
            new_name='todoFilter',
        ),
    ]
